fieldLayouts:
  2afb147d-aa6e-46d2-860a-c7bfdecdc2a6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 4171cbec-44b2-4114-b94a-f9252a27a202
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 71616991-7357-4326-a812-50fe9892f288 # Tagline
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 216db44c-b1df-4894-a3c7-0502257650e0
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1d1952d6-121c-435d-a696-1b15a682572d
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 59b7e146-e8a9-4b01-8c5b-96cdb9126900 # Projects
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
