defaultPlacement: end
fieldLayouts:
  02719ec6-1cfd-4ad1-b2ba-3e8fe7da9900:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 729e7c45-905e-4c8a-9baa-452e64046941
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8847e8c4-03a2-4e06-bb02-b3deaf62ca87
        userCondition: null
handle: projectTypes
name: 'Project Types'
siteSettings:
  9a47d3d4-06fa-448c-a974-f78b60fab694: # Zodiakagency Craft
    hasUrls: true
    template: _pages/projects.twig
    uriFormat: 'projects/{slug}'
structure:
  maxLevels: 1
  uid: e1d863d9-d6f1-45c8-bb07-ea414de8612d
