fieldLayouts:
  6acbb37f-4668-4c8d-8eec-57ea583fb2ec:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: af7c1f9c-b3af-4df3-a0f7-b63ae4e79a9f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3fa437a4-74e0-4731-8f89-888763cd454f
        userCondition: null
fs: projectsImages
handle: projectsImages
name: 'Projects Images'
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
