columnSuffix: bpjdrvzx
contentColumnType: string(256)
fieldGroup: 35e61bba-1b91-425a-b722-8e59a00d6ca9 # globals
handle: companyPhoneMachines
instructions: null
name: 'Company Phone (machines)'
searchable: false
settings:
  byteLimit: null
  charLimit: 64
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
