columnSuffix: null
contentColumnType: string
fieldGroup: 633fee1d-baee-40f7-a100-07339748b36f # home
handle: homeBanner
instructions: null
name: Banner
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: false
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:b003f777-25b4-4ecf-90b5-3e954ca2dc8a' # Projects Images
  defaultUploadLocationSubpath: null
  localizeRelations: false
  maxRelations: 1
  minRelations: 1
  previewMode: thumbs
  restrictFiles: true
  restrictLocation: true
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:15de42af-6dbd-42c1-99d2-a54309eda276' # Banners Images
  restrictedLocationSubpath: null
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Asset
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\assets\AssetCondition
  selectionLabel: 'Add banner image'
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  source: null
  sources: '*'
  targetSiteId: null
  validateRelatedElements: true
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
