columnSuffix: dvhczjxn
contentColumnType: string(1020)
fieldGroup: 633fee1d-baee-40f7-a100-07339748b36f # home
handle: homeIntro
instructions: null
name: Intro
searchable: false
settings:
  byteLimit: null
  charLimit: 255
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
