columnSuffix: null
contentColumnType: string
fieldGroup: 255693df-55b5-4718-9ddb-68fa1ada246d # projects
handle: projectImage
instructions: "Upload a landscape JPG image (1500\_x 1125)"
name: Image
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: false
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:b003f777-25b4-4ecf-90b5-3e954ca2dc8a' # Projects Images
  defaultUploadLocationSubpath: null
  localizeRelations: false
  maxRelations: 1
  minRelations: 1
  previewMode: thumbs
  restrictFiles: true
  restrictLocation: true
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:b003f777-25b4-4ecf-90b5-3e954ca2dc8a' # Projects Images
  restrictedLocationSubpath: null
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Asset
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\assets\AssetCondition
  selectionLabel: null
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  source: null
  sources: '*'
  targetSiteId: null
  validateRelatedElements: true
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
