columnSuffix: null
contentColumnType: string
fieldGroup: 255693df-55b5-4718-9ddb-68fa1ada246d # projects
handle: projectTypes
instructions: null
name: Types
searchable: false
settings:
  allowLimit: false
  allowMultipleSources: false
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showSiteMenu: false
  source: 'group:69df7443-c58f-4525-a798-63aa468b875d' # Project Types
  sources: '*'
  targetSiteId: null
  validateRelatedElements: true
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
