dateModified: 1671036552
elementSources:
  craft\elements\Entry:
    -
      key: '*'
      type: native
    -
      heading: PAGES
      type: heading
    -
      defaultSort:
        - title
        - asc
      disabled: false
      key: singles
      tableAttributes:
        - link
      type: native
    -
      heading: Channels
      type: heading
    -
      defaultSort:
        - postDate
        - desc
      disabled: false
      key: 'section:59b7e146-e8a9-4b01-8c5b-96cdb9126900' # Projects
      tableAttributes:
        - postDate
        - expiryDate
        - link
      type: native
    -
      heading: Navigations
      type: heading
    -
      key: 'section:b84caf5d-ef5a-4d0b-9fc0-853488a722af' # Main Navigation
      type: native
email:
  fromEmail: jercoupe@gmail.com
  fromName: 'Zodiakagency Craft'
  transportType: craft\mail\transportadapters\Sendmail
fs:
  bannersImages:
    hasUrls: true
    name: 'Banners Images'
    settings:
      path: '@assetsBasePath/banners_images'
    type: craft\fs\Local
    url: '@assetsBaseUrl/banners_images/'
  projectsImages:
    hasUrls: true
    name: 'Projects Images'
    settings:
      path: '@assetsBasePath/projects_images'
    type: craft\fs\Local
    url: '@assetsBaseUrl/projects_images'
meta:
  __names__:
    0a1ccdef-776e-4489-b7a0-5bab7115bcdf: 'We do Intro' # We do Intro
    0d0272f3-d1ad-49c0-ba42-20d339e3ec04: 'Page Big Title' # Page Big Title
    1abc90c2-f3ed-49ba-8f78-719dba025d77: Label # Label
    1c3447b9-a7d1-4204-8679-8f2834116750: Default # Default
    1c129203-3226-44df-8661-e261ba8feca9: 'Home Page' # Home Page
    3c1b24b7-6b22-4438-9eaf-b55e31583a22: Body # Body
    3d3b4e08-cec8-4e1f-9bcb-9568a9e497c5: 'Projects Title' # Projects Title
    4a1c4956-1ede-43de-9eda-66723840b588: 'Public Schema' # Public Schema
    4b02ef51-9918-44e9-bb7d-d3f324f3f3f5: Types # Types
    5af42c9e-fb57-4c1b-b4ae-7c1329c92a09: nav # nav
    5b092f20-28c2-421f-be74-7c3893256787: Image # Image
    5c0d7253-aa51-4fa6-b09b-e2242694fd9c: Text # Text
    5e368438-8cd5-45ea-a482-68e78c333062: Banner # Banner
    6e183543-3b5d-4c57-a0e4-4d62256d797f: ID # ID
    6ef3fe51-685a-4e26-8de6-9bb92fc4e7e0: Skills # Skills
    7d818f4b-12b3-4cd5-a3a2-1d7e7795d121: Content # Content
    8bdc33b9-d070-4f3f-ba4e-8b60a1ada3b6: Service # Service
    9a47d3d4-06fa-448c-a974-f78b60fab694: 'Zodiakagency Craft' # Zodiakagency Craft
    15de42af-6dbd-42c1-99d2-a54309eda276: 'Banners Images' # Banners Images
    18ff1bed-af09-450d-a02f-2eb6f57a5866: Title # Title
    35e61bba-1b91-425a-b722-8e59a00d6ca9: globals # globals
    38f18d43-4e11-4e76-9729-419ed6ad83b1: 'Facebook Url' # Facebook Url
    39c11757-82e2-471c-b1c4-39afd5421466: Image # Image
    57d5d656-f1bc-4e49-b6e7-237035606edb: Image # Image
    59b7e146-e8a9-4b01-8c5b-96cdb9126900: Projects # Projects
    69df7443-c58f-4525-a798-63aa468b875d: 'Project Types' # Project Types
    73b8bb2b-a2a8-4834-93ef-1217eca41937: Title # Title
    83f58274-9755-4238-9912-b837fdfc3a97: 'Linked Entry' # Linked Entry
    93ad530f-87db-431e-84ff-3354ac3f7bc8: Caption # Caption
    449be26e-8b98-441f-bc09-53e89ffdd755: 'Social Media' # Social Media
    605fda05-d777-4511-9412-031b126e3c31: 'Home Page' # Home Page
    633fee1d-baee-40f7-a100-07339748b36f: home # home
    715fe2d6-a473-4909-be0a-efaa2280709c: Introduction # Introduction
    6303d516-27d1-4c46-a262-8961d263c2eb: Intro # Intro
    255693df-55b5-4718-9ddb-68fa1ada246d: projects # projects
    71616991-7357-4326-a812-50fe9892f288: Tagline # Tagline
    a0371bee-a5e1-4a17-a84b-f7649c0d2868: 'About Page' # About Page
    a7687043-975c-4f08-8cfd-156d3bbe21bd: 'Projects page' # Projects page
    ab4ca841-ee46-4f8d-9bd5-0ad4ed598c73: 'We do title' # We do title
    b003f777-25b4-4ecf-90b5-3e954ca2dc8a: 'Projects Images' # Projects Images
    b84caf5d-ef5a-4d0b-9fc0-853488a722af: 'Main Navigation' # Main Navigation
    bbb88a10-79f6-4e02-987b-330fa874eb7e: Default # Default
    bc1649ee-a883-4a06-ba32-280da43d1797: Skill # Skill
    c9c650ec-7fd2-4941-b966-d82f4e449846: 'About Page' # About Page
    c744faa3-eb71-40a7-a09c-1e84c44145bd: Caption # Caption
    c26390ae-27ab-44a4-b520-d231a9a51e38: Description # Description
    cc467438-c5ba-458f-9ebc-b49b5f094d25: 'Projects page' # Projects page
    cf2e8d9c-d608-4aa8-955c-91e5111f9985: 'Projects Intro' # Projects Intro
    eb57f4c8-ab1b-49ab-8751-319e54b8fac2: 'Zodiakagency Craft' # Zodiakagency Craft
    f601f0d9-7321-460b-b47d-7f130933e31f: 'Instagram Url' # Instagram Url
    f684ff07-12b7-4d89-a0b8-4431a99fa54a: Common # Common
    f5104fef-fb08-4a11-82fa-39fe8d154b17: 'Twitter Url' # Twitter Url
    f4813703-9dc8-4eee-8e2a-4fae65788277: Video # Video
plugins:
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
system:
  edition: pro
  live: true
  name: 'Zodiakagency Craft'
  schemaVersion: 4.0.0.9
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
