fieldLayouts:
  1b972e2c-ed7b-426e-8bff-4e8c973f68ae:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 38f18d43-4e11-4e76-9729-419ed6ad83b1 # Facebook Url
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3ddea407-09b0-4f34-a731-037c1b1c6c2e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f601f0d9-7321-460b-b47d-7f130933e31f # Instagram Url
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a6ebda7c-5cd8-403a-9b84-98666aef41da
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f5104fef-fb08-4a11-82fa-39fe8d154b17 # Twitter Url
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ad92cf2d-fea0-443d-865d-aaad684c3222
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ef6dcd42-572a-4bfe-b44a-569b1a7e08e3
        userCondition: null
handle: socialMedia
name: 'Social Media'
sortOrder: 1
