defaultPlacement: end
enableVersioning: true
handle: homePage
name: homepage
propagationMethod: all
siteSettings:
  9a47d3d4-06fa-448c-a974-f78b60fab694: # Zodiakagency Craft
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
