defaultPlacement: end
enableVersioning: true
handle: projects
name: Projects
propagationMethod: all
siteSettings:
  9a47d3d4-06fa-448c-a974-f78b60fab694: # Zodiakagency Craft
    enabledByDefault: true
    hasUrls: true
    template: projects/_entry.twig
    uriFormat: 'margotte/{slug}'
type: channel
